version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: booklibrary-postgres
    environment:
      POSTGRES_DB: booklibrary
      POSTGRES_USER: booklibrary
      POSTGRES_PASSWORD: booklibrary123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - booklibrary-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booklibrary -d booklibrary"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WildFly Application Server
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booklibrary-wildfly
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: booklibrary
      DB_USER: booklibrary
      DB_PASSWORD: booklibrary123
    networks:
      - booklibrary-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/book-library/api/books"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: booklibrary-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@booklibrary.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - booklibrary-network
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  booklibrary-network:
    driver: bridge 